
job:
  runModel:

    parameters:
      t0_date: "2025-02-01"
      projection_period: 24

    inputs:
      augmented_config: "inputs/structured_run_config.yaml"
      customer_loans: "inputs/loan_final313_100.csv"

    outputs:
      simulated_loans: "outputs/structured_objects/simulated_loans.csv"
