# Copyright 2022 Accenture Global Solutions Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config:
  secret.type: PKCS12
  secret.url: secrets.p12


repositories:
  UNIT_TEST_REPO:
    protocol: git
    properties:
      repoUrl: ${CURRENT_GIT_ORIGIN}


executor:

  protocol: SSH
  properties:
    remoteHost: executor
    remotePort: 2222
    batchUser: linuxserver.io
    keyFile: trac_ci_rsa.pem
    venvPath: /opt/trac/venv
    batchDir: /opt/trac/jobs

